project:
  type: website
  execute-dir: project
  output-dir: docs

language: 
  search-box-placeholder: Search

format:
  html:
    page-layout: full
    # df-print: paged
    toc: true
    number-depth: 4
    theme: default
    css: 
      - "www/assets/css/styles_quarto.css"
    common-ext-css:
      - "//use.fontawesome.com/releases/v5.0.6/css/all.css"
    fig-align: center
    text-align: justify
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    linkcolor: "#16b1bf"
    fontsize: "14pt"
    include-after-body: www/hubspot.html
      
website:
  title: "Kyle Barrett"
  image: "www/assets/FB_profile.jpg"
  open-graph: true
  favicon: "www/assets/FB_profile.jpg"
  twitter-card:
    creator: "@barrettk"
  repo-url: https://github.com/barrettk/barrettk.github.io
  google-analytics: G-P7X9T3WX06
  cookie-consent: true
  search:
    location: sidebar
    copy-button: true
    type: textbox
    show-item-context: root
  sidebar:
    title: Navigation
    border: true
    contents:
      - text: Home
        href: index.html
        icon: bank
      - section: "Software Development"
        href: software.html
        contents:
          - section: "Professional Development"
            contents:
              - text: "Metrum Research Group"
                href: software.html#metrum-research-group
              - text: "Certara"
                href: software.html#certara
          - section: "Personal Projects & Github Repositories"
            contents:
              - text: "pythonR R package"
                href: software.html#pythonr
              - text: "songClip R package"
                href: software.html#songclip
              - text: "Archived Projects"
                href: software.html#archived-projects
      - text: "Research & Publications"
        href: research.html
  navbar:
    background: "white"
    foreground: "black"
    right:
      - text: "Home"
        href: index.html
      - text: "{{< fa brands github size=Large >}}"
        href: https://github.com/barrettk
      - text: "{{< fa brands researchgate size=Large >}}"
        href: https://www.researchgate.net/profile/Kyle_Barrett6
      - text: "{{< fa brands linkedin size=Large >}}"
        href: https://www.linkedin.com/in/kyle-barrett-434926b9/
      - text: "Repositories"
        menu:
          - text: "---"
          - text: "Personal Projects"
          - text: "---"
          - text: "pythonR"
            href: https://barrettk.github.io/pythonR/
          - text: "songClip"
            href: https://mlvisions.github.io/songClip/
          - text: "Anerobic Digestion"
            href: https://barrettk.github.io/AnaerobicDigestion/
          - text: "Kombucha Brewing"
            href: https://barrettk.github.io/KombuchaBrewing/
            
          - text: "---"
          - text: "Proffesional Development"
          - text: "---"
          - text: "bbr"
            href: https://metrumresearchgroup.github.io/bbr/
          - text: "pmforest"
            href: https://metrumresearchgroup.github.io/pmforest/
          - text: "mpn.scorecard"
            href: https://metrumresearchgroup.github.io/mpn.scorecard/
          - text: "mrgda"
            href: https://metrumresearchgroup.github.io/mrgda/
          - text: "nmrec"
            href: https://metrumresearchgroup.github.io/nmrec/
  page-footer:
    left: |
      Personal Portfolio
    center:
      - text: "Home"
        href: index.html
    right:
      - text: "{{< fa brands github size=Large >}}"
        href: https://github.com/barrettk/barrettk.github.io
        aria-label: Repository GitHub
      - text: "{{< fa brands researchgate size=Large >}}"
        href: https://www.researchgate.net/profile/Kyle_Barrett6
      - text: "{{< fa brands linkedin size=Large >}}"
        href: https://www.linkedin.com/in/kyle-barrett-434926b9/
        
        