---
title: "Research & Publications"
title-block-banner: '#007319'
title-block-banner-color: white
toc: false
---

<br>

### Selected publications

Huang Z, Barrett JS, **Barrett K**, Barrett R, Ng, CM. Novel method to predict body weight in children based on age and morphological facial features. *The Journal of Clinical Pharmacology*, 2015; 55: 447–451.

Huang Z, Barrett JS, **Barrett K**, Barrett R, Ng, CM. Estimation of Body Weight in Children Based on Age and Morphological Facial Features. *AAPS Annual Meeting and Exposition*, At San Diego, CA 2014

Cimorelli M, Angel B, Fafarman A, Kohut A, Andrien B, **Barrett K**, Wrenn SP. Introducing a nested phase change agent with an acoustic response that depends on electric field: A candidate for myocardial perfusion imaging and drug delivery. *Applied Acoustics*, 2018: 138: 9-17.

Barrett JS, Spitsin S, Moorthy G, **Barrett K**, Baker K, Lackner A, Tulic F, Winters A, Evans DL, Douglas SD. Pharmacologic rationale for the NK1R antagonist, Aprepitant as adjunctive therapy in HIV. *J Transl Med*. 2016;14:148

Barrett JS, Moorthy WD, Srivastata G, **Barrett K**, Spitsin KJ, Tuluc S, et al. Preclinical activity predicts higher dosing requirements for the NK-1r antagonist Aprepitant in HIV-associated neurocognitive disorders (HAND): Dispositional and pharmacologic rationale for multimodal therapeutic window. *Clin Pharmacol Therapeut* 2013; 93 Suppl 1:S17.PI-9.

Cimorelli M, Andrien B, **Barrett K**, Fafarman A, Kohut A, Wrenn S. Electric Field Activation of Nested Ultrasound Contrast Agents: In Vitro and In Vivo Investigations. *ACS: Colloid & Surface Science Symposium*, At City College of New York, 2017; 91

Elmokadem A, Gastonguay M, Baron K, **Barrett K**, Zane N, Yankee T, Riggs M. Application of an Open- source Physiologically-based Pharmacokinetic Model of Voriconazole to Explore Apparent Pharmacokinetic Differences between Adults and Children. CPT: *Pharmacometrics and Systems Pharmacology*, 2018 (Submitted)

More information and additional publications can be found on [Research Gate](https://www.researchgate.net/profile/Kyle_Barrett6).
